#!/bin/bash
# 🔥 ESP8266 WiFi-Verbindungsprobleme ENDGÜLTIG lösen!

echo "🚨 ESP8266 WiFi-Debugging - Täglich grüßt das Murmeltier!"
echo "========================================================="

echo ""
echo "🔍 SCHRITT 1: WiFi-Netzwerk prüfen"
echo "-----------------------------------"
echo "1. Router-Name/SSID prüfen:"
iwconfig 2>/dev/null || echo "iwconfig nicht verfügbar"
nmcli dev wifi list 2>/dev/null || echo "nmcli nicht verfügbar"

echo ""
echo "2. Aktuelle WiFi-Verbindung:"
ip route | grep default

echo ""
echo "🔧 SCHRITT 2: Häufigste ESP8266 WiFi-Probleme"
echo "--------------------------------------------"
echo "❌ PROBLEM 1: Falsche SSID/Passwort im Code"
echo "   → ESP8266-Code prüfen: WiFi.begin(ssid, password)"
echo ""
echo "❌ PROBLEM 2: 5GHz WiFi (ESP8266 kann nur 2.4GHz!)"
echo "   → Router auf 2.4GHz-Band prüfen"
echo ""
echo "❌ PROBLEM 3: Versteckte SSID" 
echo "   → Router SSID-Broadcast aktivieren"
echo ""
echo "❌ PROBLEM 4: WPA3-Verschlüsselung (ESP8266 = WPA/WPA2 only!)"
echo "   → Router auf WPA2 umstellen"
echo ""
echo "❌ PROBLEM 5: MAC-Filter aktiv"
echo "   → ESP8266 MAC-Adresse im Router freischalten"
echo ""
echo "❌ PROBLEM 6: Zu schwaches WiFi-Signal"
echo "   → ESP8266 näher zum Router"

echo ""
echo "🛠️  SCHRITT 3: ESP8266 Serial Monitor Debugging"
echo "-----------------------------------------------"
echo "1. Arduino IDE → Serial Monitor (115200 baud)"
echo "2. ESP8266 Reset/Neustart"
echo "3. WiFi-Debug-Meldungen lesen:"
echo ""
echo "   ✅ ERFOLG-Meldungen:"
echo "      'WiFi connected'"
echo "      'IP address: 192.168.2.20'"
echo "      'Static IP configured'"
echo ""
echo "   ❌ FEHLER-Meldungen:"
echo "      'WiFi connection failed'"
echo "      'No networks found'"
echo "      'Wrong password'"
echo "      'Timeout connecting'"

echo ""
echo "⚡ SCHRITT 4: SOFORT-FIX Versuche"
echo "--------------------------------"
echo "1. Router neustarten (Strom weg 30s)"
echo "2. ESP8266 neustarten (Reset-Button)" 
echo "3. Anderen 2.4GHz-Kanal (1, 6, 11) am Router"
echo "4. Router WiFi-Modus auf 'gemischt 2.4GHz + 5GHz'"
echo "5. Temporär Router-Gastnetzwerk aktivieren"

echo ""
echo "🔥 SCHRITT 5: NOTFALL-LÖSUNG - Access Point Modus"
echo "------------------------------------------------"
echo "Falls WiFi-Station nicht geht:"
echo "1. ESP8266 Web-UI: http://192.168.4.1/"
echo "2. Access Point 'ESP8266-HX711' suchen"
echo "3. Mit Handy/Laptop verbinden"
echo "4. WiFi-Konfiguration über Web-Interface"

echo ""
echo "📋 DEBUGGING-CHECKLISTE:"
echo "========================"
echo "□ Serial Monitor Ausgabe gelesen?"
echo "□ Router 2.4GHz aktiv?" 
echo "□ WPA2-Verschlüsselung (nicht WPA3)?"
echo "□ SSID sichtbar (nicht versteckt)?"
echo "□ ESP8266 in Router-Nähe?"
echo "□ Richtiges WiFi-Passwort im Code?"
echo "□ Router neugestartet?"
echo "□ ESP8266 neugestartet?"

echo ""
echo "💡 TIPP: Handy-Hotspot als Test"
echo "==============================="
echo "Schnelltest mit Handy-Hotspot:"
echo "1. Handy-Hotspot: Name='TEST', Passwort='12345678'"
echo "2. ESP8266-Code anpassen: WiFi.begin('TEST', '12345678')"  
echo "3. Flashen und testen"
echo "4. Wenn das geht → Router-Problem!"
echo ""
echo "🎯 Ziel: ESP8266 soll zeigen: 'Static IP: 192.168.2.20'"