#!/bin/bash
# 🚨 ESP8266 Access Point Problem - er läuft, aber nicht im richtigen Netzwerk!

echo "🔥 ESP8266 ACCESS POINT PROBLEM LÖSEN"
echo "====================================="
echo ""
echo "🎯 SYMPTOM: ESP8266 Web-UI läuft, aber Pi5 findet ihn nicht!"
echo "📊 HX711-Daten sind da → ESP8266 Hardware OK"
echo "❌ WiFi Station-Modus failed → ESP8266 läuft als Access Point"
echo ""

echo "🔍 DIAGNOSE:"
echo "-----------"
echo "ESP8266 ist vermutlich erreichbar unter:"
echo "🌐 Access Point: http://192.168.4.1/"
echo "📱 WiFi-Netz: 'ESP8266-HX711' oder ähnlich"
echo ""

echo "💡 SOFORT-FIX 1: Access Point finden"
echo "-----------------------------------"
echo "1. Mit Handy/Laptop WiFi-Netze scannen"
echo "2. Suche nach: 'ESP8266', 'NodeMCU', 'ESP_XXXXXX'"
echo "3. Verbinde dich damit (meist kein Passwort)"
echo "4. Browser: http://192.168.4.1/"
echo "5. WiFi-Konfiguration eingeben!"
echo ""

echo "💡 SOFORT-FIX 2: Serial Monitor"
echo "------------------------------"
echo "Arduino IDE Serial Monitor (115200 baud):"
echo "1. ESP8266 Reset drücken"
echo "2. Suche nach Meldungen:"
echo "   'WiFi connection failed'"
echo "   'Starting Access Point'"
echo "   'AP IP: 192.168.4.1'"
echo ""

echo "🛠️  LÖSUNG: WiFi-Credentials korrigieren"
echo "---------------------------------------"
echo "Im Arduino-Code (esp8266_dual_hx711_simple.ino):"
echo ""
echo "const char* ssid = \"IHR_WIFI_NAME\";"
echo "const char* password = \"IHR_WIFI_PASSWORT\";"
echo ""
echo "HÄUFIGE FEHLER:"
echo "❌ Falscher WiFi-Name (SSID)"
echo "❌ Falsches Passwort" 
echo "❌ 5GHz statt 2.4GHz"
echo "❌ WPA3 statt WPA2"
echo ""

echo "⚡ QUICK-TEST mit Handy-Hotspot:"
echo "------------------------------"
echo "1. Handy-Hotspot aktivieren: Name='TEST', Passwort='12345678'"
echo "2. Arduino-Code ändern:"
echo '   const char* ssid = "TEST";'
echo '   const char* password = "12345678";'
echo "3. ESP8266 flashen"
echo "4. Sollte sich verbinden und 192.168.2.20 bekommen"
echo ""

echo "🎯 ERFOLG-KRITERIUM:"
echo "==================="
echo "Serial Monitor zeigt:"
echo "✅ 'WiFi connected'"
echo "✅ 'IP address: 192.168.2.20'"
echo "✅ 'Static IP configured'"
echo ""

echo "📱 WiFi-Netze scannen:"
iwconfig 2>/dev/null | grep ESSID || echo "Kein iwconfig verfügbar"
echo ""
echo "🔍 Suche ESP8266 Access Point mit Handy/Laptop!"